##Q1 creation
import sqlite3
conn=sqlite3.connect("test.db")
print("database connected sucessfully")
'''conn.execute("create TABLE Book(bookID INTEGER PRIMARY KEY not null,Title_Id INTEGER not null,Location text,Gerne text)")
print("table book created")
conn.execute("create TABLE Titles(TitleID INTEGER PRIMARY KEY not null,isbn INTEGER not null,publisher_id INTEGER,publishyear INTEGER)")
print("table Titles created")
conn.execute("create TABLE publishers(Publisher_id INTEGER PRIMARY KEY not null,Name text not null,Street Address STRING,Suite INTEGER,Zipid INTEGER)")
print("table Publisher created")
conn.execute("create TABLE ZIP_Codes(Zipid INTEGER PRIMARY KEY not null,City text not null,State text,ZipCode INTEGER)")
print("table ZipCodes created")
conn.execute("create TABLE Authortitles(Authortitle_id INTEGER PRIMARY KEY not null,AuthorID INTEGER not null,Title_Id INTEGER)")
print("table Author titles created")
conn.execute("create TABLE Author(AuthorID INTEGER PRIMARY KEY not null,FirstName text not null,MiddleName text,LastName text)")
print("table author created")

##Q2 insertion
conn.execute("INSERT INTO Book VALUES(11,111,'science section','technical')")
conn.execute("INSERT INTO Book VALUES(23,131,'Arts section','fiction')")
conn.execute("INSERT INTO Book VALUES(18,143,'History section','story')")
conn.commit()
print("inserted sucessfully A")
conn.execute("INSERT INTO Titles VALUES(111,1520,45,1996)")
conn.execute("INSERT INTO Titles VALUES(131,1521,46,1997)")
conn.execute("INSERT INTO Titles VALUES(143,1674,32,1891)")
conn.commit()
print("inserted sucessfully B")
conn.execute("INSERT INTO publishers VALUES(45,'Arya publishers','chandni chowk',13,110001)")
conn.execute("INSERT INTO publishers VALUES(46,'laxmi publication','educatin socity',25,110042)")
conn.execute("INSERT INTO publishers VALUES(32,'ABC Publication','nehru palace',19,170001)")
conn.commit()
print("inserted sucessfully C")
conn.execute("INSERT INTO ZIP_Codes VALUES(110001,'Delhi','Delhi',01)")
conn.execute("INSERT INTO ZIP_Codes VALUES(110042,'Vizag','AP',02)")
conn.execute("INSERT INTO ZIP_Codes VALUES(170001,'Shimla','HP',03)")
conn.commit()
print("inserted sucessfully D")
conn.execute("INSERT INTO Authortitles VALUES(1101,91,111)")
conn.execute("INSERT INTO Authortitles VALUES(1108,95,131)")
conn.execute("INSERT INTO Authortitles VALUES(1199,99,143)")
conn.commit()
print("inserted sucessfully E")
conn.execute("INSERT INTO Author VALUES(91,'DR','RD','sharma')")
conn.execute("INSERT INTO Author VALUES(95,'sumitra','lal','pant')")
conn.execute("INSERT INTO Author VALUES(99,'Br','kumar','sharma')")
conn.commit()
print("inserted sucessfully F")'''


###Q3 table updation

currsor=conn.execute("SELECT * from Author")
print('table before updation')
for i in currsor:
    print("AuthorID=", i[0])
    print("first name=", i[1])
    print("midle name=", i[2])
    print("last name=", i[3], "\n")
print("record created suceesfully")
conn.execute("UPDATE Author set MiddleName = 'nandan' where AuthorID = 95")
print("table after updation")
d=conn.execute("SELECT * from Author where AuthorID=95")
for j in d:
    print("AuthorID=", j[0])
    print("first name=", j[1])
    print("midle name=", j[2])
    print("last name=", j[3], "\n")
print("record updated seuccesfully")